### ISSUE TITLE
Subscribe / Unsubscribe issue

### ISSUE THREAD

**Issue by bachig26** [Sommerwiesel/invidious#7] opened 2022-12-14 05:40 UTC
The Subscribe / Unsubscribe function is not working as expected.
I found that this is only present in your invidious instance.

When I try to unsubscribe a channel, it doesn't unsubscribe and the button stays as the same, the refresh doesn't affect anything.

@Sommerwiesel 
Please have a look at the issue.

**Comment by Sommerwiesel** [comment] 2022-12-14 06:23
Cannot verify and reproduce this Problem.
I'm using my instance personally and never Bad this issue.
Moreover, I'm only changing the CSS of Invidious in my instance, everything else is Vanilla.

Please check your computer/Webbrowser, it cannot be an issue with my instance.

Therefore closed

**Comment by Sommerwiesel** [comment] 2022-12-14 06:36
If you're willing, you could send me your Browser logs and I'll habe a look and try to find out whats wrong.
You can Export them via developer tools.

Please check that nothing in your Browser is somehow blocking requests / scripts from my instance.

**Comment by arekf** [comment] 2022-12-14 09:14
The issue is with unsubscribing channels via API. The following API request returns 403:
`DELETE https://invidious.nerdvpn.de/api/v1/auth/subscriptions/{channel id}`

Other authenticated endpoints using non-DELETE methods seem to work fine for me using the same credentials.

**Comment by Sommerwiesel** [comment] 2022-12-14 09:59
Hello again,
NGINX seems to have blocked the request due to missing/authentication context.
I found a fix for this and applied it.
Could you please try again and report back?

@arekf @bachig26

**Comment by arekf** [comment] 2022-12-14 10:00
@Sommerwiesel thanks, just checked and it worked fine this time.

**Comment by Sommerwiesel** [comment] 2022-12-14 10:01
Cool, I will close the issue then.
Have a nice week :)

**Closed by Sommerwiesel** 2022-12-14 10:01 UTC
